### ISSUE TITLE
can you support ```js  when i insert code block ?

### ISSUE THREAD

**Issue by stfenjobs** [lingjieee/fantasy-editor#2]
https://fantasy-editor.jieee.dev/examples/full

i can enter \```,then enter space button, it's work

then i enter  \```js  or   \```javascript  or  \```python  ,  then enter space button, it's not work

can you  fix it ?

thank you very much

=====
中文版：
你好，我想插入代码块 ， 但是编辑器只支持 \```,   不支持设定特定语言，如 \```js , \```python ,

如果我在 \```后面加了特定语言的标记， 按空格后，没有自动生成一个代码块

请问有办法解决吗

谢谢

**Comment by lingjieee** [comment]
Thanks for your suggestion, now it's supported

**Comment by stfenjobs** [comment]
thank you
