### ISSUE TITLE
怎么添加自定义图标

### ISSUE THREAD

**Issue by find456789** [lingjieee/fantasy-editor#6]
我想在现有图标后面，添加一个问号图标， 点击图标后，就会显示 编辑器的使用说明， 请问怎么操作呢

有点类似 这个编辑器后面的问号 https://canner.github.io/canner-slate-editor/?selectedKind=canner-slate-editor&selectedStory=Simple%20demo&full=0&addons=1&stories=1&panelRight=0
![image](https://user-images.githubusercontent.com/6580897/87179285-1278fa00-c311-11ea-9bac-03837ee6c59d.png)

谢谢

**Comment by lingjieee** [comment]
你可以在<Toolbar/>组件内添加图标以及相应的动作
